### ISSUE TITLE
Inheritance of PHG4ProjCrystalCalorimeterDetector

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#102]
cppcheck showed a lot of shadowed variables. I assume it started as a plain copy of the PHG4CrystalCalorimeterDetector base class. This is just the wrong way of going about inheriting and this needs to be fixed before this propagates into other code. To run cppcheck:

cppcheck --enable=all PHG4ProjCrystalCalorimeterDetector.cc

(this also prints out style warnings which are irrelevant). Another issue is the wrong order of includes. One ALWAYS has to put the includes which use quotes (#include "...") first. Otherwise the intended search path (using local inludes first) when using separate include install directories does not work! In implementations one often gets away with it but in header files this is fatal and is extremely hard to debug.

**Comment by mccumbermike** [comment]
The issue here is the unnecessary protected declarations in the parent class. One should really use private for storage members by default and call the public interface in the daughter class.

**Comment by blackcathj** [comment]
Closed via pull request #103
