### ISSUE TITLE
Outdated code in PHG4CylinderGeom_Spacalv3?

### ISSUE THREAD

**Issue by plexoos** [sPHENIX-Collaboration/coresoftware#1048]
This file `coresoftware/simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3_2015.cc` has 18k LOC and takes a significant time to compile. For those of us who prefer to work with local builds and make sure all dependencies are rebuilt, it is noticeable.

If it is not used in any active studies now (2015 right?), it should be removed. Of course, everyone interested in this file can find it in the git history and restore if needed.

(By looking at the content of the file it appears this should have been a data file with a minimal interface to initialize the data structs)

**Comment by pinkenburg** [comment]
As far as I know this is part of the prototype sims.
In terms of compilation speedup, have a look at ccache. It does a good job speeding up the compilation significantly. In general this code should be recompiled rarely if things change - it does not have too many dependencies.

**Comment by plexoos** [comment]
I use cmake to build all libraries in coresoftware/simulation/g4simulation. Without this file all compiles under 3 minutes, and in 4.5 minutes with it. With these timings ccache is not very relevant (I also switch work trees often) and would add an unnecessary overhead. The delay is probably at the linking stage where build parallelization is not very efficient. This file does not deserve an extra investigation :)

I don't understand the argument about the number of dependencies... I don't want to think about them at all, I just know that they exist and the build system is supposed to take care of them which it does.

**Comment by blackcathj** [comment]
Done
