### ISSUE TITLE
Bad Tracking Performance

### ISSUE THREAD

**Issue by mccumbermike** [sPHENIX-Collaboration/coresoftware#147]
Somehow a bug got into the tracking in the past 10 days or so. Here is a comparison of the current performance versus what I had on 04/28 that I made over the weekend:
![crosscheck](https://cloud.githubusercontent.com/assets/12105552/15117467/ea49bb08-15c4-11e6-873e-ee6e85eb5b1f.png)

This was first reported to me by Tony on Friday, and others are noticing so I thought I'd start a ticket so others can follow the process of getting this fixed. I'm hoping around in the git history to find the culprit commit. I've already ruled out Chris's latest g4hit production changes as the source. Next I will rollback through the G4 updates and try to replicate the performance on 04/28 after we submitted the vertexing changes.

**Comment by mccumbermike** [comment]
I've made some progress on the investigation today. I was able to recreate the good tracking performance in the tutorial virtual machine I setup on 4/7/2016. Boy am I happy to have that around. I then moved forward in time through the latest commits to HelixHough and g4simulation---all the way up to the present (bfee90b). I had to revert 7216790 since I'm still using the old G4 10.2.0 code. I also checked the latest 7 layers MAPS macro... and nothing I tried replicated the momentum problem that I see always with the latest build. So as far as I can tell the bug simply isn't in HelixHough or the g4simulation or the latest MAPS macro. 

So what does that leave us:
(1) software updates outside of HelixHough or g4simulations
(2) G4, CLHEP version changes.
(3) macro changes outside of G4_Svtx_maps_7layers.C
(4) ...maybe something I'm not thinking of...

![screen shot 2016-05-12 at 2 38 01 pm](https://cloud.githubusercontent.com/assets/12105552/15229707/80158dec-184f-11e6-8804-69cfa2b2932d.png)

The small changes in the performance are from the updated macro description between the old G4_Svtx_ITS.C and G4_Svtx_maps_7layers.C.

**Comment by adfrawley** [comment]
Mike and I have both looked at the play build and the tracking bug is not present. Make sure to do "distclean" in your build areas. I have checked the Upsilon mass resolution and got 95 MeV for the 7 layer MAPS tracker, as expected. Mike checked the G4 tracking simulations and they also look fine.

**Comment by mccumbermike** [comment]
Chris and I have narrowed in on the culprit, which ended up being the new version of Eigen. We just posted a new build with the problem fixed. Here is the performance:

![screen shot 2016-05-17 at 2 14 03 pm](https://cloud.githubusercontent.com/assets/12105552/15333957/f20c7b16-1c39-11e6-99ea-11d59b232d2c.png)
