### ISSUE TITLE
PHG4CylinderGeom_MAPS class lacks public constructor

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#232]
I got this message when running the new maps+itt+tpc macro:
Warning in <TBufferFile::WriteObjectAny>: since PHG4CylinderGeom_MAPS has no public constructor
	which can be called without argument, objects of this class
	can not be read with the current library. You will need to
	add a default constructor before attempting to read it.

root calls the default ctor without arguments when reading objects back from file. One option to fix this  would be to give the existing ctor default arguments.

**Comment by mccumbermike** [comment]
I would also add to Chris's suggestion that I've found good practice in these cases to be hiding the default constructor within a protected block so that users are still directed to declare their arguments explicitly.
