### ISSUE TITLE
Remove of non-unique and non-active branches? 

### ISSUE THREAD

**Issue by blackcathj** [sPHENIX-Collaboration/coresoftware#24]
@mccumbermike , there is a few branches left in the repository, which do no carry unique commit after their pull requests. 

Shall we remove these branches? I think usually GitHub would prompt us to do so after a pull request is approved to merge these branches into the master. 

These branches include: 
* JETRECO
* PHPythia8
* evaldevel
* tower/cluseter-ids

I hope this help improve clarity to users who are looking for the official branch and the branches that carries the soon-to-come new features.

**Comment by mccumbermike** [comment]
So long as the master is unaffected (aka the commits from those branches remain in master), I say go for it.

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by blackcathj** [comment]
Removed these four development branches, which have finished their purpose of carrying development previews. 
* JETRECO
* PHPythia8
* evaldevel
* tower/cluseter-ids

Now we have two development branches which intend to merge into master soon:
* CaloTower: proposed by @nfeege 
* TPC: proposed by @alandion
