### ISSUE TITLE
secondary PHG4Particle removed, but produced PHG4Hit with no energy is not

### ISSUE THREAD

**Issue by mccumbermike** [sPHENIX-Collaboration/coresoftware#26]
So this is a funny one I ran into with the new calorimeter evaluator. I see many g4hits with zero energy in the calorimeter (I thought those were pruned). But then I come to a secondary truth particle that I suspect only left zero energy g4hits, it is a rare case anyway, and the g4particle which was added to the map before is found to be missing by eval time.

The end result is a truth hit that doesn't trace anywhere. Maybe someone turned off or disrupted the zero energy hit pruning but left the track pruning on. I can of course easily ignore g4hits with no energy deposit---that would work---but this must be a space issue for the pro.beta tag.

Can someone confirm that they see zero energy g4hits remaining in the output?

**Comment by pinkenburg** [comment]
the zero energy hits were a result using the end of event action which 
drops them incorrectly. It needs to be run for both the detector hits 
and the absorber hits but it only ran on one node. I restructured the 
code which should fix this for the future - even if another node is 
added for whatever reason. I also consolidated all those cut and paste 
event actions into a single class which is now used everywhere

On 08/23/2015 11:00 AM, Michael P. McCumber wrote:
>
> So this is a funny one I ran into with the new calorimeter evaluator. 
> I see many g4hits with zero energy in the calorimeter (I thought those 
> were pruned). But then I come to a secondary truth particle that I 
> suspect only left zero energy g4hits, it is a rare case anyway, and 
> the g4particle which was added to the map before is found to be 
> missing by eval time.
>
> The end result is a truth hit that doesn't trace anywhere. Maybe 
> someone turned off or disrupted the zero energy hit pruning but left 
> the track pruning on. I can of course easily ignore g4hits with no 
> energy deposit---that would work---but this must be a space issue for 
> the pro.beta tag.
>
> Can someone confirm that they see zero energy g4hits remaining in the 
> output?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/coresoftware/issues/26>.
>


-- 

*********************************************************

Christopher H. Pinkenburg      ; pinkenburg@bnl.gov

Brookhaven National Laboratory ; phone: (631) 344-5692
Physics Department Bldg 510 C  ; fax:   (631) 344-3253
Upton, NY 11973-5000

http://www.phenix.bnl.gov/~pinkenbu/

*********************************************************
