### ISSUE TITLE
PHRandomSeed to use rc RANDOMSEED flag?

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#46]
Let me just put this out here. We have a lot of duplicated code where you only get a PHRandomSeed if the recoconst flag RANDOMSEED is not set. Should we integrate this functionality into PHRandomSeed? That would require either moving this to fun4all (and code changes to include this file from #include <phool/PHRandomSeed.h> to <fun4all/PHRandomSeed.h>  or moving the recoconst code to phool with changing that include path in our code. Our code base is not so large that this is a catastrophe. I would prefer to move this to phool since those flags are not really part of fun4all.

I would also change the seed type to int and return the abs() so G4 is happy with whatever comes back from this.

**Comment by mccumbermike** [comment]
Seems reasonable to me.

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by mccumbermike** [comment]
Should we have the ability to increment-by-one between calls to the proposed object (giving option of having a fix and different random number seed for all modules). I'm not entirely sure I'm comfortable with the current fixed option that gives the same seed to all our random generators (which are now using very similar implementations).

**Comment by pinkenburg** [comment]
the random seed is not cached and each call to PHRandomSeed will create 
a fresh random number from /dev/urandom so each random number generator 
gets its own random seed. That's a feature we should preserve. Setting 
the RANDOMSEED flag is only for debugging where you want reproducible 
results and then I don't think this matters, given that we use one for 
the particle generator (often calling it multiple times for various 
smearing) and the next one is the G4 internal one and then maybe more in 
some smearing in the reco software. I doubt that they stay in sync in a 
way which would cause problems (any deterministic way to set the random 
seed might cause this as well).

On 9/21/2015 8:05 PM, Michael P. McCumber wrote:
>
> Should we have the ability to increment-by-one between calls to the 
> proposed object (giving option of having a fix and different random 
> number seed for all modules). I'm not entirely sure I'm comfortable 
> with the current fixed option that gives the same seed to all our 
> random generators (which are now using very similar implementations).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/coresoftware/issues/46#issuecomment-142142803>.
>

-- 
*************************************************************

Christopher H. Pinkenburg	;    pinkenburg@bnl.gov
				;    http://www.phenix.bnl.gov/~pinkenbu

Brookhaven National Laboratory	;    phone: (631) 344-5692
Physics Department Bldg 510 C	;    fax:   (631) 344-3253
Upton, NY 11973-5000

*************************************************************
