### ISSUE TITLE
infinite loop in calo evaluator for inner hcal in hijing

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#52]
I started to run over /gpfs02/phenix/prod/sPHENIX/preCDR/pro.1-beta.3/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_0200.root using the standard Fun4All_G4_sPHENIX.C macro with readhits=true and the jeteval disabled. It runs now for 10 hours, attaching with the debugger indicates it is still at the first event. It seems to be in an infinite loop in CaloTruthEval.C line 171:
  for (PHG4HitContainer::ConstIterator g4iter = _g4hits->getHits().first;
       g4iter != _g4hits->getHits().second;
       ++g4iter) {

    PHG4Hit* g4hit = g4iter->second;
    PHG4Particle* candidate = get_primary_particle(g4hit);
    if (candidate->get_track_id() != primary->get_track_id()) continue;
    truth_hits.insert(g4hit);
  }

the code doesn't seem to find a match for the candidate and keeps "continuing"

**Comment by mccumbermike** [comment]
I've been poking at this issue for the past hour or so. I don't think it
isn't truly infinite, but semi-infinite for sure. It doesn't spend much
time here until you throw hijing at it. I'm sure this has to do with
redefining the sense of primary to include both primaries on the PrimaryMap
and the copies on the Map. Which was needed to get the vertex retrieval
working.

More later.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by pinkenburg** [comment]
yes it is not infinite. I set a breakpoint after this loop and the code eventually made it there

**Comment by pinkenburg** [comment]
I timed the first event in this file and it needs 15 minutes (without jet eval). That's comparable with simulating a hijing event. Therefore we should consider to run this either as part of the hijing simulation production or better in a separate centralized pass.

**Comment by mccumbermike** [comment]
I'll have some patches soon. I had to develop a correctness test procedure
so I can follow when the eval is making incorrect decisions under load.
Throw in a lot of noise towers and things get difficult to debug by eye,
but dealing with those is also essential.

Some of the speed issues in central events came from tracing primary
"copies" stored in Map separately from primaries in the Primary Map. I
think by extending the trace all the way to the PrimaryMap (which is
smaller and has faster look up) I can improve both the caching and do my
searches on a smaller map. Apologies for the inconvenience I hadn't
expected the format of the primary "copies" to change when additional
vertexes were present.

Anyway I'm continuing to push on this today...

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by mccumbermike** [comment]
With the latest pull request #59, I think I've hit all the low hanging fruit and some of the harder to reach items. If additional speed is needed during heavy ion production, I propose to limit the evaluation to scales above 2.0 GeV/c or so.

Feel free to reopen this if there is something else you think I can do.
