### ISSUE TITLE
PHG4UIsession.cc suppresses overlap warnings

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#53]
Ultimately it's a bad design in G4 - if one enables checks for overlaps in G4PVPlacement, G4 sends the output (OK or not OK) to stdout instead of errors to stderr. Those messages are essential and we cannot suppress them for any verbosity level. I changed the code that it pipes again everything to stdout independent of verbosity level. I left the rest intact - if we find a solution for this we can switch this back.

**Comment by pinkenburg** [comment]
changed
if (verbosity > 0) std::cout << coutString << std::flush;
to 
  //  if (verbosity > 0) std::cout << coutString << std::flush;
  std::cout << coutString << std::flush;

**Comment by mccumbermike** [comment]
No objection. Too bad G4 doesn't follow the rules. Other than string-matching particular annoying messages... which sounds like bad design (this isn't called but a few time per job typically, so it would work)... I don't think there is another way to go.
