### ISSUE TITLE
a clone repository  in case-insensitive filesystem does not work as expected...

### ISSUE THREAD

**Issue by ycorrales** [sPHENIX-Collaboration/coresoftware#570]
Cloning in case-insensitive filesystem (e.g default MacOS filesystem) case-sensitive path groups collide and only one from the same colliding group is in the working tree while the second appears always as no staged changes....

case-sensitive groups:
  'offline/packages/mvtx/MVTXClusterizer.cc'
  'offline/packages/mvtx/MvtxClusterizer.cc'
  'offline/packages/mvtx/MVTXClusterizer.h'
  'offline/packages/mvtx/MvtxClusterizer.h'
  'offline/packages/mvtx/MVTXClusterizerLinkDef.h'
  'offline/packages/mvtx/MvtxClusterizerLinkDef.h'
  'simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc'
  'simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc'
  'simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h'
  'simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.h'
  'simulation/g4simulation/g4mvtx/PHG4MVTXDigitizerLinkDef.h'
  'simulation/g4simulation/g4mvtx/PHG4MvtxDigitizerLinkDef.h'

**Comment by pinkenburg** [comment]
That must have happened during some reorganisation (this definitely not intentional). I asked Tony to take care of this
