### ISSUE TITLE
nodenames cannot contain decimal points

### ISSUE THREAD

**Issue by pinkenburg** [sPHENIX-Collaboration/coresoftware#96]
It's not explicitly mentioned and I never really thought about it but decimal points in node names interfere with the DST readback. We store the node names as branch names together with their parent PHCompositeNodes which are separated by decimal points. Compared to the slashes used in PHENIX this enables us to call methods on those nodes from the CINT cmd line. If a node name contains a decimal point it interferes with the restoring of the node tree making an identical restore impossible. Original Node Tree during sim:
         CLUSTER (PHCompositeNode)/
            AntiKt_Cluster_r0.2 (PHIODataNode)
            AntiKt_Cluster_r0.3 (PHIODataNode)
            AntiKt_Cluster_r0.4 (PHIODataNode)
            AntiKt_Cluster_r0.5 (PHIODataNode)

Reconstructed nodes from DST:
         CLUSTER (PHCompositeNode)/
            AntiKt_Cluster_r0 (PHCompositeNode)/
               2 (PHIODataNode)
               3 (PHIODataNode)
               4 (PHIODataNode)
               5 (PHIODataNode)

I put a check for this on my todo list (bail out if someone tries to create a node with a name containing a decimal point)

**Comment by pinkenburg** [comment]
I just added the check. From the next build on tomorrow 2pm the code will bail out if a node name contains a decimal point. I prefer that over stripping the decimal point which will just confuse people in the long run

**Comment by pinkenburg** [comment]
I just changed the G4_jets.C macro where those names are set (stripping the decimal point from the names). The macro runs through but it needs to be checked if this is what should be done

**Comment by mccumbermike** [comment]
Sorry for being unresponsive this morning, I haven't been feeling well. I'm
pretty sure that is the only place the names are utilized. The jet
containers understand what the radii are by storing a float, so I think we
should be free to rename as we please. Just remember to scroll down and
rename the evaluation input so it understands where things went.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by blackcathj** [comment]
The DST node name of the Flowjet Module was also fixed via this commit (https://github.com/sPHENIX-Collaboration/analysis/commit/65a3ad5358d1c3ecf81ea2ce282d2179b8624f03 ) . 

Problem solved, closing this issue.

**Comment by blackcathj** [comment]
Problem solved, closing this issue.
